services:
  postgres12:
    image: postgres:12.20-alpine3.20
    container_name: postgres12
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=curso
    networks:
      - curso
    restart: always
  ms-producto-03:
    image: ms-producto:02-run
    container_name: ms-producto-03
    environment:
      - URL=jdbc:postgresql://postgres12:5432/curso
      - USER_DB=postgres
      - PASS_DB=123456
      - PORT=8082
    networks:
      - curso
    restart: always
    depends_on:
      - postgres12
  nginx:
    container_name: proxy
    image: nginx:lates
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./privkey.pem:/etc/nginx/ssl/privkey.pem
    depends_on:
      - ms-producto-03
networks:
  curso:
    external: true
