FROM openjdk:26-ea-21-jdk-oraclelinux8

RUN mkdir /app
RUN adduser test

COPY target/*.jar /app/app.jar
COPY run.sh app/run.sh

RUN chmod +x app/run.sh
RUN chown -R test:test /app

USER test
WORKDIR /app

# Ejecuta cuando se inicia el contenedor
ENTRYPOINT ["./run.sh"]
