server {
    listen 443 ssl;
    server_name www.yoursite.com;
    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location / {
        proxy_pass http://ms-producto-03:8082
        error_log /var/log/front_end_errors.log
    }
}
